apiVersion: 1
datasources:
  - name: VPS Prometheus
    uid: vps-prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: false
    editable: false
    jsonData:
      timeInterval: 30s
  - name: Airflow Monitoring
    uid: airflow-monitoring
    type: postgres
    access: proxy
    url: postgres:5432
    user: airflow_monitor
    editable: false
    jsonData:
      database: airflow
      sslmode: disable
      postgresVersion: 1500
      maxOpenConns: 3
    secureJsonData:
      password: $DATA_ANALYST_PASSWORD
